# SPDX-FileCopyrightText: 2026 Mattia Egloff <mattia.egloff@pm.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later

version = 1
SPDX-PackageName = "vauchi-relay"
SPDX-PackageSupplier = "Mattia Egloff <mattia.egloff@pm.me>"

# License files
[[annotations]]
path = ["LICENSES/**"]
SPDX-FileCopyrightText = "Free Software Foundation"
SPDX-License-Identifier = "GPL-3.0-or-later"

# Lock files
[[annotations]]
path = ["**/Cargo.lock", "**/*.lock"]
SPDX-FileCopyrightText = "2026 Mattia Egloff <mattia.egloff@pm.me>"
SPDX-License-Identifier = "GPL-3.0-or-later"

# Git and editor config files
[[annotations]]
path = [".gitignore", "**/.gitignore", ".DS_Store", "**/.gitkeep"]
SPDX-FileCopyrightText = "2026 Mattia Egloff <mattia.egloff@pm.me>"
SPDX-License-Identifier = "GPL-3.0-or-later"

# JSON config files
[[annotations]]
path = ["**/*.json"]
SPDX-FileCopyrightText = "2026 Mattia Egloff <mattia.egloff@pm.me>"
SPDX-License-Identifier = "GPL-3.0-or-later"
